import { useEffect, useState } from 'react';
import api from '../../services/api';
import { formatCurrency, formatDate } from '../../utils/formatters';
import { Button } from '../../components/Button';
import { Modal } from '../../components/Modal';
import { PrintButton } from '../../components/PrintButton';
import { printContent } from '../../utils/print';
import { useSettings } from '../../hooks/useSettings';
import { useAdminAuth } from '../../hooks/useAuth';

export const Accounts = () => {
  const [balance, setBalance] = useState(0);
  const [totalIn, setTotalIn] = useState(0);
  const [totalOut, setTotalOut] = useState(0);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [incomeModal, setIncomeModal] = useState(false);
  const [expenseModal, setExpenseModal] = useState(false);
  const [incomeForm, setIncomeForm] = useState({ description: '', amount: '' });
  const [expenseForm, setExpenseForm] = useState({ description: '', amount: '' });
  const { settings } = useSettings();
  const { user } = useAdminAuth();

  const fetchData = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/accounts/balance');
      setBalance(data.balance || 0);
      setTotalIn(data.totalIn || 0);
      setTotalOut(data.totalOut || 0);
      setTransactions(data.transactions || []);
    } catch (err) {
      console.error('Error fetching accounts data:', err);
      setBalance(0);
      setTotalIn(0);
      setTotalOut(0);
      setTransactions([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const addIncome = async () => {
    if (!incomeForm.description || !incomeForm.amount || parseFloat(incomeForm.amount) <= 0) {
      alert('Please fill all fields with valid amount');
      return;
    }
    try {
      await api.post('/accounts/income', {
        amount: parseFloat(incomeForm.amount),
        description: incomeForm.description
      });
      setIncomeModal(false);
      setIncomeForm({ description: '', amount: '' });
      fetchData();
    } catch (err) {
      alert(err.response?.data?.message || 'Error adding income');
    }
  };

  const addExpense = async () => {
    if (!expenseForm.description || !expenseForm.amount || parseFloat(expenseForm.amount) <= 0) {
      alert('Please fill all fields with valid amount');
      return;
    }
    try {
      await api.post('/accounts/expense', {
        amount: parseFloat(expenseForm.amount),
        description: expenseForm.description
      });
      setExpenseModal(false);
      setExpenseForm({ description: '', amount: '' });
      fetchData();
    } catch (err) {
      alert(err.response?.data?.message || 'Error adding expense');
    }
  };

  const printTransaction = (tx) => {
    const html = `
      <h2>TRANSACTION VOUCHER</h2>
      <table style="width: 100%; margin: 20px 0;">
          <tr><td style="padding: 8px;"><strong>Voucher No:</strong></td><td>${tx._id}</td></tr>
          <tr><td style="padding: 8px;"><strong>Date:</strong></td><td>${formatDate(tx.date)}</td></tr>
          <tr><td style="padding: 8px;"><strong>Type:</strong></td><td>${tx.type === 'in' ? 'Income' : 'Expense'}</td></tr>
          <tr><td style="padding: 8px;"><strong>Description:</strong></td><td>${tx.description}</td></tr>
          <tr><td style="padding: 8px;"><strong>Amount:</strong></td><td>${formatCurrency(tx.amount)}</td></tr>
          <tr><td style="padding: 8px;"><strong>Generated By:</strong></td><td>${user?.name || 'Admin'}</td></tr>
      </table>
    `;
    printContent(html, `Voucher_${tx._id}`, settings);
  };

  if (loading) return <div className="text-center py-10">Loading accounts...</div>;

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">Accounts</h1>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div className="card text-center bg-gradient-to-r from-green-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Current Balance</p>
          <p className={`text-3xl font-bold ${balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
            {formatCurrency(balance)}
          </p>
        </div>
        <div className="card text-center bg-gradient-to-r from-blue-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Total Income</p>
          <p className="text-3xl font-bold text-primary">{formatCurrency(totalIn)}</p>
        </div>
        <div className="card text-center bg-gradient-to-r from-red-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Total Expenses</p>
          <p className="text-3xl font-bold text-danger">{formatCurrency(totalOut)}</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 mb-6">
        <Button onClick={() => setIncomeModal(true)}>➕ Add Income</Button>
        <Button variant="secondary" onClick={() => setExpenseModal(true)}>💸 Add Expense</Button>
      </div>

      {/* Transactions List */}
      <div className="card">
        <h2 className="text-xl font-semibold mb-4">Transaction History</h2>
        {transactions.length === 0 ? (
          <p className="text-gray-500 text-center py-8">No transactions yet. Add income or expenses to get started.</p>
        ) : (
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {transactions.map((tx) => (
              <div
                key={tx._id}
                className={`flex justify-between items-center p-3 rounded-lg border-l-4 ${
                  tx.type === 'in' ? 'border-green-500 bg-green-50' : 'border-red-500 bg-red-50'
                }`}
              >
                <div className="flex-1">
                  <p className="font-medium">{formatDate(tx.date)}</p>
                  <p className="text-sm text-gray-600">{tx.description}</p>
                </div>
                <div className="flex items-center gap-4">
                  <span className={`font-bold ${tx.type === 'in' ? 'text-green-600' : 'text-red-600'}`}>
                    {tx.type === 'in' ? '+' : '-'}{formatCurrency(tx.amount)}
                  </span>
                  <PrintButton onClick={() => printTransaction(tx)}>Print</PrintButton>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Income Modal */}
      <Modal isOpen={incomeModal} onClose={() => setIncomeModal(false)} title="Add Income">
        <div className="mb-4">
          <label className="block mb-1 font-medium">Description *</label>
          <input
            type="text"
            className="w-full border p-2 rounded"
            value={incomeForm.description}
            onChange={(e) => setIncomeForm({ ...incomeForm, description: e.target.value })}
            placeholder="e.g., Student fees, Service charge"
          />
        </div>
        <div className="mb-6">
          <label className="block mb-1 font-medium">Amount (KES) *</label>
          <input
            type="number"
            step="any"
            className="w-full border p-2 rounded"
            value={incomeForm.amount}
            onChange={(e) => setIncomeForm({ ...incomeForm, amount: e.target.value })}
            placeholder="Enter amount"
          />
        </div>
        <Button onClick={addIncome} className="w-full">Record Income</Button>
      </Modal>

      {/* Expense Modal */}
      <Modal isOpen={expenseModal} onClose={() => setExpenseModal(false)} title="Add Expense">
        <div className="mb-4">
          <label className="block mb-1 font-medium">Description *</label>
          <input
            type="text"
            className="w-full border p-2 rounded"
            value={expenseForm.description}
            onChange={(e) => setExpenseForm({ ...expenseForm, description: e.target.value })}
            placeholder="e.g., Electricity bill, Internet subscription"
          />
        </div>
        <div className="mb-6">
          <label className="block mb-1 font-medium">Amount (KES) *</label>
          <input
            type="number"
            step="any"
            className="w-full border p-2 rounded"
            value={expenseForm.amount}
            onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })}
            placeholder="Enter amount"
          />
        </div>
        <Button onClick={addExpense} className="w-full">Record Expense</Button>
      </Modal>
    </div>
  );
};