import { useEffect, useState } from 'react';
import api from '../../services/api';
import { formatCurrency, formatDate } from '../../utils/formatters';
import { Button } from '../../components/Button';
import { Modal } from '../../components/Modal';
import { PrintButton } from '../../components/PrintButton';
import { printContent } from '../../utils/print';
import { useSettings } from '../../hooks/useSettings';
import { useAdminAuth } from '../../hooks/useAuth';
import { FeeStructureModal } from '../../components/FeeStructureModal';

export const Accounts = () => {
  const [balance, setBalance] = useState(0);
  const [totalIn, setTotalIn] = useState(0);
  const [totalOut, setTotalOut] = useState(0);
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [incomeModal, setIncomeModal] = useState(false);
  const [expenseModal, setExpenseModal] = useState(false);
  const [incomeForm, setIncomeForm] = useState({ description: '', amount: '' });
  const [expenseForm, setExpenseForm] = useState({ description: '', amount: '' });
  const [feeModalOpen, setFeeModalOpen] = useState(false); // <-- ADDED
  const { settings } = useSettings();
  const { user } = useAdminAuth();

  const fetchData = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/accounts/balance');
      setBalance(data.balance || 0);
      setTotalIn(data.totalIn || 0);
      setTotalOut(data.totalOut || 0);
      setTransactions(data.transactions || []);
    } catch (err) {
      console.error('Error fetching accounts data:', err);
      setBalance(0);
      setTotalIn(0);
      setTotalOut(0);
      setTransactions([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const addIncome = async () => {
    if (!incomeForm.description || !incomeForm.amount || parseFloat(incomeForm.amount) <= 0) {
      alert('Please fill all fields with valid amount');
      return;
    }
    try {
      await api.post('/accounts/income', {
        amount: parseFloat(incomeForm.amount),
        description: incomeForm.description
      });
      setIncomeModal(false);
      setIncomeForm({ description: '', amount: '' });
      fetchData();
    } catch (err) {
      alert(err.response?.data?.message || 'Error adding income');
    }
  };

  const addExpense = async () => {
    if (!expenseForm.description || !expenseForm.amount || parseFloat(expenseForm.amount) <= 0) {
      alert('Please fill all fields with valid amount');
      return;
    }
    try {
      await api.post('/accounts/expense', {
        amount: parseFloat(expenseForm.amount),
        description: expenseForm.description
      });
      setExpenseModal(false);
      setExpenseForm({ description: '', amount: '' });
      fetchData();
    } catch (err) {
      alert(err.response?.data?.message || 'Error adding expense');
    }
  };

  const printTransaction = (tx) => {
    const now = new Date();
    const schoolName = settings?.schoolName || 'HDM Computer School';
    const address = settings?.address || '';
    const html = `
      <div style="max-width: 600px; margin: 0 auto;">
        <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">
          ${schoolName}
        </h1>
        <p style="text-align: center;">${address}</p>
        <hr/>
        <h2>Transaction Voucher</h2>
        <p><strong>Voucher No:</strong> ${tx._id}</p>
        <p><strong>Date:</strong> ${formatDate(tx.date)}</p>
        <p><strong>Type:</strong> ${tx.type === 'in' ? 'Income' : 'Expense'}</p>
        <p><strong>Description:</strong> ${tx.description}</p>
        <p><strong>Amount:</strong> ${formatCurrency(tx.amount)}</p>
        <p><strong>Generated By:</strong> ${user?.name || 'Admin'}</p>
        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px;">
          <p><strong>${schoolName}</strong> | ${address}</p>
          <p>Printed: ${now.toLocaleString()}</p>
          <p>${settings?.motto || 'Technology for Tomorrow'}</p>
        </div>
      </div>
    `;
    printContent(html, `Voucher_${tx._id}`);
  };

  if (loading) return <div className="text-center py-10">Loading accounts...</div>;

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">Accounts</h1>
      
      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        <div className="card text-center bg-gradient-to-r from-green-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Current Balance</p>
          <p className={`text-3xl font-bold ${balance >= 0 ? 'text-green-600' : 'text-red-600'}`}>
            {formatCurrency(balance)}
          </p>
        </div>
        <div className="card text-center bg-gradient-to-r from-blue-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Total Income</p>
          <p className="text-3xl font-bold text-primary">{formatCurrency(totalIn)}</p>
        </div>
        <div className="card text-center bg-gradient-to-r from-red-50 to-white">
          <p className="text-gray-500 text-sm uppercase">Total Expenses</p>
          <p className="text-3xl font-bold text-danger">{formatCurrency(totalOut)}</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-4 mb-6 flex-wrap">
        <Button onClick={() => setIncomeModal(true)}>➕ Add Income</Button>
        <Button variant="secondary" onClick={() => setExpenseModal(true)}>💸 Add Expense</Button>
        <Button variant="secondary" onClick={() => setFeeModalOpen(true)}>📄 Fee Structure</Button> {/* <-- ADDED */}
      </div>

      {/* Transactions List */}
      <div className="card">
        <h2 className="text-xl font-semibold mb-4">Transaction History</h2>
        {transactions.length === 0 ? (
          <p className="text-gray-500 text-center py-8">No transactions yet. Add income or expenses to get started.</p>
        ) : (
          <div className="space-y-2 max-h-96 overflow-y-auto">
            {transactions.map((tx) => (
              <div 
                key={tx._id} 
                className={`flex justify-between items-center p-3 rounded-lg border-l-4 ${
                  tx.type === 'in' ? 'border-green-500 bg-green-50' : 'border-red-500 bg-red-50'
                }`}
              >
                <div className="flex-1">
                  <p className="font-medium">{formatDate(tx.date)}</p>
                  <p className="text-sm text-gray-600">{tx.description}</p>
                  {tx.reference && <p className="text-xs text-gray-400">Ref: {tx.reference}</p>}
                </div>
                <div className="flex items-center gap-4">
                  <span className={`font-bold ${tx.type === 'in' ? 'text-green-600' : 'text-red-600'}`}>
                    {tx.type === 'in' ? '+' : '-'}{formatCurrency(tx.amount)}
                  </span>
                  {tx.amount > 0 && <PrintButton onClick={() => printTransaction(tx)}>Print</PrintButton>}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Income Modal */}
      <Modal isOpen={incomeModal} onClose={() => setIncomeModal(false)} title="Add Income">
        <div className="mb-4">
          <label className="block mb-1 font-medium">Description *</label>
          <input
            type="text"
            className="w-full border p-2 rounded focus:outline-none focus:ring-2 focus:ring-primary"
            value={incomeForm.description}
            onChange={(e) => setIncomeForm({ ...incomeForm, description: e.target.value })}
            placeholder="e.g., Student fees, Service charge"
          />
        </div>
        <div className="mb-6">
          <label className="block mb-1 font-medium">Amount (KES) *</label>
          <input
            type="number"
            step="any"
            className="w-full border p-2 rounded focus:outline-none focus:ring-2 focus:ring-primary"
            value={incomeForm.amount}
            onChange={(e) => setIncomeForm({ ...incomeForm, amount: e.target.value })}
            placeholder="Enter amount"
          />
        </div>
        <Button onClick={addIncome} className="w-full">Record Income</Button>
      </Modal>

      {/* Expense Modal */}
      <Modal isOpen={expenseModal} onClose={() => setExpenseModal(false)} title="Add Expense">
        <div className="mb-4">
          <label className="block mb-1 font-medium">Description *</label>
          <input
            type="text"
            className="w-full border p-2 rounded focus:outline-none focus:ring-2 focus:ring-primary"
            value={expenseForm.description}
            onChange={(e) => setExpenseForm({ ...expenseForm, description: e.target.value })}
            placeholder="e.g., Electricity bill, Internet subscription"
          />
        </div>
        <div className="mb-6">
          <label className="block mb-1 font-medium">Amount (KES) *</label>
          <input
            type="number"
            step="any"
            className="w-full border p-2 rounded focus:outline-none focus:ring-2 focus:ring-primary"
            value={expenseForm.amount}
            onChange={(e) => setExpenseForm({ ...expenseForm, amount: e.target.value })}
            placeholder="Enter amount"
          />
        </div>
        <Button onClick={addExpense} className="w-full">Record Expense</Button>
      </Modal>

      {/* Fee Structure Modal */}
      <FeeStructureModal isOpen={feeModalOpen} onClose={() => setFeeModalOpen(false)} />
    </div>
  );
};