import { useState } from 'react';
import api from '../../services/api';
import { formatCurrency, formatDate, formatShortDate } from '../../utils/formatters';
import { Button } from '../../components/Button';
import { printContent } from '../../utils/print';
import { useSettings } from '../../hooks/useSettings';
import { useAdminAuth } from '../../hooks/useAuth';

export const Reports = () => {
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [reportType, setReportType] = useState('students');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const { settings } = useSettings();
  const { user } = useAdminAuth();

  const generateReport = async () => {
    setLoading(true);
    try {
      if (reportType === 'students') {
        const res = await api.get('/students');
        setData(res.data);
      } else if (reportType === 'employees') {
        const res = await api.get('/employees');
        setData(res.data);
      } else if (reportType === 'fees') {
        const res = await api.get('/fees');
        setData(res.data);
      } else if (reportType === 'inventory') {
        const res = await api.get('/inventory');
        setData(res.data);
      } else if (reportType === 'financial') {
        if (!fromDate || !toDate) {
          alert('Please select both dates');
          setLoading(false);
          return;
        }
        const res = await api.get('/accounts/transactions');
        const filtered = res.data.filter(t => new Date(t.date) >= new Date(fromDate) && new Date(t.date) <= new Date(toDate));
        setData(filtered);
      }
    } catch (err) {
      console.error(err);
      alert(err.response?.data?.message || 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const printReport = () => {
    if (!data) return;

    const schoolName = settings?.schoolName || 'HDM Computer School';
    const motto = settings?.motto || 'Technology for Tomorrow';
    const address = settings?.address || '';
    const phone = settings?.phone || '';
    const email = settings?.email || '';
    const now = new Date();
    const generatedBy = user?.name || 'Admin';

    let html = '';

    if (reportType === 'students') {
      html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif;">
          <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">${schoolName}</h1>
          <p style="text-align: center; font-style: italic; margin: 5px 0;">${motto}</p>
          <p style="text-align: center; margin: 5px 0;">${address}</p>
          <p style="text-align: center; margin: 5px 0;">📞 ${phone} | ✉️ ${email}</p>
          <hr/>
          <h2 style="text-align: center;">OFFICIAL STUDENT REPORT</h2>
          <p><strong>Generated:</strong> ${now.toLocaleString()}</p>
          <p><strong>Generated By:</strong> ${generatedBy}</p>
          <p><strong>Total Students:</strong> ${data.length}</p>
          <hr/>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd;">Reg No</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Name</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Course</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Fees Paid</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Balance</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Computer</th>
               </tr>
            </thead>
            <tbody>
              ${data.map(s => {
                const courseFee = settings?.courses?.find(c => c.name === s.course)?.totalFee || 0;
                const balance = courseFee - s.feesPaid;
                return `
                  <tr style="border-bottom: 1px solid #ddd;">
                    <td style="padding: 8px; border: 1px solid #ddd;">${s.regNumber}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${s.name}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${s.course}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(s.feesPaid)}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(balance)}</td>
                    <td style="padding: 8px; border: 1px solid #ddd;">${s.computerAssigned || '-'}</td>
                  </tr>
                `;
              }).join('')}
            </tbody>
          </table>
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px; color: #666;">
            <p><strong>${schoolName}</strong> | ${address}</p>
            <p>Printed: ${now.toLocaleString()} | Generated By: ${generatedBy}</p>
            <p style="margin-top: 10px; font-style: italic;">${motto}</p>
          </div>
        </div>
      `;
    } 
    else if (reportType === 'employees') {
      html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif;">
          <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">${schoolName}</h1>
          <p style="text-align: center; font-style: italic; margin: 5px 0;">${motto}</p>
          <p style="text-align: center; margin: 5px 0;">${address}</p>
          <p style="text-align: center; margin: 5px 0;">📞 ${phone} | ✉️ ${email}</p>
          <hr/>
          <h2 style="text-align: center;">OFFICIAL EMPLOYEE REPORT</h2>
          <p><strong>Generated:</strong> ${now.toLocaleString()}</p>
          <p><strong>Generated By:</strong> ${generatedBy}</p>
          <p><strong>Total Employees:</strong> ${data.length}</p>
          <hr/>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd;">Employee ID</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Name</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Duty</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Salary</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Payment Method</th>
               </tr>
            </thead>
            <tbody>
              ${data.map(e => `
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 8px; border: 1px solid #ddd;">${e.empId}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${e.name}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${e.duty}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(e.salary)}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${e.paymentMethod}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px; color: #666;">
            <p><strong>${schoolName}</strong> | ${address}</p>
            <p>Printed: ${now.toLocaleString()} | Generated By: ${generatedBy}</p>
            <p style="margin-top: 10px; font-style: italic;">${motto}</p>
          </div>
        </div>
      `;
    }
    else if (reportType === 'fees') {
      html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif;">
          <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">${schoolName}</h1>
          <p style="text-align: center; font-style: italic; margin: 5px 0;">${motto}</p>
          <p style="text-align: center; margin: 5px 0;">${address}</p>
          <p style="text-align: center; margin: 5px 0;">📞 ${phone} | ✉️ ${email}</p>
          <hr/>
          <h2 style="text-align: center;">OFFICIAL FEES REPORT</h2>
          <p><strong>Generated:</strong> ${now.toLocaleString()}</p>
          <p><strong>Generated By:</strong> ${generatedBy}</p>
          <p><strong>Total Payments:</strong> ${data.length}</p>
          <hr/>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd;">Date</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Student</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Reg No</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Amount Paid</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Balance After</th>
               </tr>
            </thead>
            <tbody>
              ${data.map(f => `
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatShortDate(f.date)}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${f.studentName}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${f.regNumber}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(f.amount)}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(f.balanceAfter)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px; color: #666;">
            <p><strong>${schoolName}</strong> | ${address}</p>
            <p>Printed: ${now.toLocaleString()} | Generated By: ${generatedBy}</p>
            <p style="margin-top: 10px; font-style: italic;">${motto}</p>
          </div>
        </div>
      `;
    }
    else if (reportType === 'inventory') {
      const totalValue = data.reduce((sum, i) => sum + i.value, 0);
      html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif;">
          <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">${schoolName}</h1>
          <p style="text-align: center; font-style: italic; margin: 5px 0;">${motto}</p>
          <p style="text-align: center; margin: 5px 0;">${address}</p>
          <p style="text-align: center; margin: 5px 0;">📞 ${phone} | ✉️ ${email}</p>
          <hr/>
          <h2 style="text-align: center;">OFFICIAL INVENTORY REPORT</h2>
          <p><strong>Generated:</strong> ${now.toLocaleString()}</p>
          <p><strong>Generated By:</strong> ${generatedBy}</p>
          <p><strong>Total Items:</strong> ${data.length}</p>
          <p><strong>Total Value:</strong> ${formatCurrency(totalValue)}</p>
          <hr/>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd;">Name</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Type</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Value</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Status</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Assigned To</th>
               </tr>
            </thead>
            <tbody>
              ${data.map(i => `
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 8px; border: 1px solid #ddd;">${i.name}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${i.type}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(i.value)}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${i.status}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${i.assignedTo ? (i.assignedModel === 'Student' ? 'Student' : 'Employee') : '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px; color: #666;">
            <p><strong>${schoolName}</strong> | ${address}</p>
            <p>Printed: ${now.toLocaleString()} | Generated By: ${generatedBy}</p>
            <p style="margin-top: 10px; font-style: italic;">${motto}</p>
          </div>
        </div>
      `;
    }
    else if (reportType === 'financial') {
      const totalIn = data.filter(t => t.type === 'in').reduce((s, t) => s + t.amount, 0);
      const totalOut = data.filter(t => t.type === 'out').reduce((s, t) => s + t.amount, 0);
      const net = totalIn - totalOut;
      html = `
        <div style="font-family: 'Segoe UI', Arial, sans-serif;">
          <h1 style="text-align: center; color: #0a2a44; border-bottom: 3px solid #2f86eb; padding-bottom: 10px;">${schoolName}</h1>
          <p style="text-align: center; font-style: italic; margin: 5px 0;">${motto}</p>
          <p style="text-align: center; margin: 5px 0;">${address}</p>
          <p style="text-align: center; margin: 5px 0;">📞 ${phone} | ✉️ ${email}</p>
          <hr/>
          <h2 style="text-align: center;">OFFICIAL FINANCIAL REPORT</h2>
          <p><strong>Period:</strong> ${fromDate} – ${toDate}</p>
          <p><strong>Generated:</strong> ${now.toLocaleString()}</p>
          <p><strong>Generated By:</strong> ${generatedBy}</p>
          <hr/>
          <h3>Summary</h3>
          <p><strong>Total Income:</strong> ${formatCurrency(totalIn)}</p>
          <p><strong>Total Expenses:</strong> ${formatCurrency(totalOut)}</p>
          <p><strong>Net Balance:</strong> ${formatCurrency(net)}</p>
          <hr/>
          <h3>Transaction Details</h3>
          <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
            <thead>
              <tr style="background-color: #f2f2f2;">
                <th style="padding: 10px; border: 1px solid #ddd;">Date</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Description</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Type</th>
                <th style="padding: 10px; border: 1px solid #ddd;">Amount</th>
               </tr>
            </thead>
            <tbody>
              ${data.map(t => `
                <tr style="border-bottom: 1px solid #ddd;">
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatShortDate(t.date)}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${t.description}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${t.type === 'in' ? 'Income' : 'Expense'}</td>
                  <td style="padding: 8px; border: 1px solid #ddd;">${formatCurrency(t.amount)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #2f86eb; text-align: center; font-size: 12px; color: #666;">
            <p><strong>${schoolName}</strong> | ${address}</p>
            <p>Printed: ${now.toLocaleString()} | Generated By: ${generatedBy}</p>
            <p style="margin-top: 10px; font-style: italic;">${motto}</p>
          </div>
        </div>
      `;
    }

    printContent(html, `${reportType.toUpperCase()}_Report`);
  };

  return (
    <div>
      <h1 className="text-2xl font-bold mb-6">Reports</h1>
      <div className="card mb-6">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
          <div>
            <label className="block mb-1">Report Type</label>
            <select
              className="w-full border p-2 rounded"
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
            >
              <option value="students">Students</option>
              <option value="employees">Employees</option>
              <option value="fees">Fees</option>
              <option value="inventory">Inventory</option>
              <option value="financial">Financial (Date Range)</option>
            </select>
          </div>
          {reportType === 'financial' && (
            <>
              <div>
                <label className="block mb-1">From Date</label>
                <input
                  type="date"
                  className="w-full border p-2 rounded"
                  value={fromDate}
                  onChange={(e) => setFromDate(e.target.value)}
                />
              </div>
              <div>
                <label className="block mb-1">To Date</label>
                <input
                  type="date"
                  className="w-full border p-2 rounded"
                  value={toDate}
                  onChange={(e) => setToDate(e.target.value)}
                />
              </div>
            </>
          )}
          <div className="flex gap-2">
            <Button onClick={generateReport} disabled={loading}>
              {loading ? 'Generating...' : 'Generate Report'}
            </Button>
            {data && (
              <Button variant="secondary" onClick={printReport}>
                🖨️ Print Report
              </Button>
            )}
          </div>
        </div>
      </div>

      {data && (
        <div className="card">
          <h2 className="text-xl font-semibold mb-4">Preview</h2>
          <pre className="bg-gray-50 p-4 rounded overflow-auto max-h-96 text-sm">
            {reportType === 'students' && data.map(s => `${s.regNumber} | ${s.name} | ${s.course} | Paid: ${formatCurrency(s.feesPaid)} | Balance: ${formatCurrency((settings?.courses?.find(c => c.name === s.course)?.totalFee || 0) - s.feesPaid)}`).join('\n')}
            {reportType === 'employees' && data.map(e => `${e.empId} | ${e.name} | ${e.duty} | ${formatCurrency(e.salary)}`).join('\n')}
            {reportType === 'fees' && data.map(f => `${formatShortDate(f.date)} | ${f.studentName} | ${f.regNumber} | ${formatCurrency(f.amount)} | Balance: ${formatCurrency(f.balanceAfter)}`).join('\n')}
            {reportType === 'inventory' && data.map(i => `${i.name} | ${i.type} | ${formatCurrency(i.value)} | ${i.status}`).join('\n')}
            {reportType === 'financial' && data.map(t => `${formatShortDate(t.date)} | ${t.description} | ${t.type === 'in' ? 'Income' : 'Expense'} | ${formatCurrency(t.amount)}`).join('\n')}
          </pre>
        </div>
      )}
    </div>
  );
};